apps/crud/models.py
from werkzeug.security import check_password_hash
from flask_login import UserMixin

from apps.app import db, login_manager


class Cafe(db.Model):
    __tablename__ = "cafes"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    address = db.Column(db.String)
    text = db.Column(db.String)



class Admin(UserMixin, db.Model):
    __tablename__ = "admins"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, unique=True)
    password_hash = db.Column(db.String)

    def __init__(self, username, password):
        self.username = username
        self.set_password(password)

    @property
    def password(self):
        return self.password_hash

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    


@login_manager.user_loader
def load_user(user_id):
    return Admin.query.get(user_id)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, InputRequired

class LoginForm(FlaskForm):
    username = StringField('사용자이름', validators=[DataRequired()])
    password = PasswordField('비밀번호', validators=[DataRequired()])
    submit = SubmitField('로그인')

class CafeForm(FlaskForm):
    name = StringField('카페 이름', validators=[InputRequired()])
    address = StringField('카페 주소', validators=[InputRequired()])
    text = TextAreaField('메모 하기')
    submit = SubmitField('추가')     

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import login_required, login_user, logout_user
from apps.crud.forms import LoginForm, CafeForm
from apps.crud.models import Cafe, Admin
from apps.app import db  


crud = Blueprint(
    "crud",
    __name__,
    template_folder = "templates",
    static_folder = "static"
)



@crud.route("/")
def index():
    return render_template('crud/index.html')

@crud.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        admin = Admin.query.filter_by(username=username).first()
        if admin and admin.password_hash == password : 
            login_user(admin)
            return redirect(url_for("crud.index"))
        
        flash("아이디 또는 비밀번호가 일치하지 않습니다.")
    return render_template("crud/login.html", form=form)


@crud.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("crud.index"))


@crud.route("/cafe_list")
def cafe_list():
    cafes = Cafe.query.all()
    return render_template('crud/cafe_list.html', cafes=cafes)


@crud.route("/add_cafe", methods=["GET", "POST"])
@login_required
def add_cafe():
    form = CafeForm()
    if form.validate_on_submit():
        if request.method == "POST":
            name = request.form["name"]
            address = request.form["address"]
            text = request.form["text"]
            new_cafe = Cafe(name=name, address=address, text=text)
            db.session.add(new_cafe)
            db.session.commit()
            return redirect(url_for("crud.cafe_list"))
        return render_template('crud/add_cafe.html')
    flash("")
    return render_template("crud/add_cafe.html", form=form)



@crud.route("/delete_cafe/<id>", methods=["POST"])
@login_required
def delete_cafe(id):
    cafe_to_delete = Cafe.query.filter_by(id=id).first()
    db.session.delete(cafe_to_delete)
    db.session.commit()
    return redirect(url_for("crud.cafe_list"))

apps/crud/templates/crud/add_cafe.html
{% extends "crud/base.html" %}
{% block title %} 카페추가 {% endblock %}
{% block content %}

<title>카페 추가하기</title>
<body class="body">
<div class="div">
   
<h2 class="title">카페 추가</h2>
<form action="{{ url_for('crud.add_cafe') }}" method="post">

{% for message in get_flashed_messages() %}
<p style="color: red;">{{ message }}</p>
{% endfor %}
{{ form.csrf_token}}

<p>
    <span class="span">{{ form.name.label }}</span>
    {{ form.name(size=30, placeholder="카페 이름")}}
</p>

{% for error in form.name.errors %}
<span style="color: white">{{ error }}</span>
{% endfor %}

<p><span class="span">{{ form.address.label }}</span> {{ form.address(placeholder="카페 주소") }}</p>
{% for error in form.address.errors %}
<span style="color: white;">{{ error }}</span>
{% endfor %}

<p>
    <span class="span">{{ form.text.label }}</span>
    {{ form.text(placeholder="메모")}}
</p>

{% for error in form.text.errors %}
<span style="color: white">{{ error }}</span>
{% endfor %}
<p><a  href="{{ url_for('crud.cafe_list')}}"><button type="submit" class="btn btn-secondary">추가</button></a></p>
<p><a class="btn btn-secondary" href="{{ url_for('crud.index')}}">메인페이지</a></p>
</form>
</div>
</body>
{% endblock %}

apps/crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} {% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('crud.static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
    <script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    {% block content %} {% endblock %}
</body>
</html>

apps/crud/templates/crud/cafe_list.html
{% extends "crud/base.html" %}
{% block title %} 대전 카페 리스트 {% endblock %}
{% block content %}
<body class="body">
<div class="div">
    <table>
        <tr>
            <td class="td">
    <h1 class="title">대전 카페 리스트</h1>

    <ul>
        {% for cafe in cafes %}
            <li class="li">
                <strong>{{ cafe.name }}</strong><br>
                주소: {{ cafe.address }}<br>
                메모: {{ cafe.text }}
            </li>
        {% endfor %}
    </ul>
            </td>
            
            <td class="td2">
    <h2 class="title">추가/삭제하기</h2>
    <ul>
    {% for cafe in cafes %}
        <li class="li2">{{ cafe.name }} - {{ cafe.address }} [ 메모: {{ cafe.text }} ] 
            <form action="{{ url_for('crud.delete_cafe', id=cafe.id) }}" method="post"><button type="submit">삭제</button></form></li>
        {% endfor %}
    </ul>
    <a class="btn btn-secondary" href="{{ url_for('crud.add_cafe') }}">카페 추가하기</a>
    <a class="btn btn-secondary" href="{{ url_for('crud.index')}}">메인페이지</a>
</td>    
</tr>
</table>
</div>
</body>
{% endblock %}

apps/crud/templates/crud/index.html
{% extends "crud/base.html" %}
{% block title %} 대전 카페 {% endblock %}
{% block content %}
<body class="body">
<div class="div">
    <h1 class="title"> 가고싶은 카페 저장하기</h1>

    {% if current_user.is_authenticated %}
        <p><a class="btn btn-secondary" href="{{ url_for('crud.logout') }}">로그아웃</a></p>
    {% else %}
        <p><a class="btn btn-secondary"href="{{ url_for('crud.login') }}">로그인</a></p>
    {% endif %}

    <p><a class="btn btn-secondary" href="{{ url_for('crud.cafe_list') }}">대전광역시 카페정보</a></p>
</div>
</body>
{% endblock %}

apps/crud/templates/crud/login.html
{% extends "crud/base.html" %}
{% block title %} 로그인 {% endblock %}
{% block content %}
<body class="body">
<div class="div">
<h2 class="title">로그인</h2>
<form action="{{ url_for('crud.login') }}" method="post" novalidate="novalidate">

    {% for message in get_flashed_messages() %}
    <p style="color: red">{{ message }}</p>
    {% endfor %}
    
    {{ form.csrf_token }}

    <p>
        <span class="span">{{ form.username.label }}</span>
        {{ form.username(placeholder="아이디") }}
        {% for error in form.username.errors %}
        <span style="color: white;">{{ error }}</span>
        {% endfor %}
    </p>

    <p>
        <span class="span"> {{ form.password.label }}</span>
        {{ form.password(placeholder="비밀번호") }}
        {% for error in form.password.errors %}
        <span style="color: white;">{{ error }}</span>
        {% endfor %}
    </p>

    <p><input class="btn btn-secondary" type="submit" value="로그인" /></p>
    <p ><a class="btn btn-secondary" href="{{ url_for('crud.index')}}">메인페이지</a></p>
</div>
</form>
</body>
{% endblock %}